export const TOAST = 'toast'
export const HOME_CONTENT_ROOT_ID = 'home-content-root'
export const NEWS_IMG_DEFAULT = '/assets/img/news_default_img.jpg'

export const USERS = {
  AUTH: 'AUTH',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  REGISTER: 'REGISTER',
  GET_USERS: 'GET_USERS',
  GET_USER: 'GET_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
  ERRORS: 'ERRORS',
  CLEAN: 'CLEAN'
}

export const PROFILE = {
  GET_PROFILE: 'GET_PROFILE',
  GET_PROFILES: 'GET_PROFILES',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  DELETE_PROFILE: 'DELETE_PROFILE',
  ERRORS: 'ERRORS',
  CLEAN: 'CLEAN'
}

export const CLASSROOM = {
  GET_CLASSROOM: 'GET_CLASSROOM',
  GET_CLASSROOMS: 'GET_CLASSROOMS',
  UPDATE_CLASSROOM: 'UPDATE_CLASSROOM',
  DELETE_CLASSROOM: 'DELETE_CLASSROOM',
  ERRORS: 'ERRORS',
  CLEAN: 'CLEAN'
}

export const STUDENT = {
  GET_STUDENT: 'GET_STUDENT',
  GET_STUDENTS: 'GET_STUDENTS',
  UPDATE_STUDENT: 'UPDATE_STUDENT',
  DELETE_STUDENT: 'DELETE_STUDENT',
  ERRORS: 'ERRORS',
  CLEAN: 'CLEAN'
}

export const STAFF = {
  GET_STAFF: 'GET_STAFF',
  GET_STAFFS: 'GET_STAFFS',
  UPDATE_STAFF: 'UPDATE_STAFF',
  DELETE_STAFF: 'DELETE_STAFF',
  ERRORS: 'ERRORS',
  CLEAN: 'CLEAN'
}

export const SCORE = {
  GET_SCORE: 'GET_SCORE',
  GET_SCORES: 'GET_SCORES',
  ADD_SCORE: 'ADD_SCORE',
  UPDATE_SCORE: 'UPDATE_SCORE',
  DELETE_SCORE: 'DELETE_SCORE',
  ERRORS: 'ERRORS',
  CLEAN: 'CLEAN'
}

export const TOAST_TYPE = {
  SUCCESS: 'success',
  ERROR: 'error',
  INFO: 'info',
  WARNING: 'warning'
}

export const ROLES = {
  STUDENT: 'student',
  STAFF: 'staff',
  TEACHER: 'teacher',
  ADMIN: 'admin'
}
