export const TOAST = 'toast'
export const HOME_CONTENT_ROOT_ID = 'home-content-root'
export const NEWS_IMG_DEFAULT = '/assets/img/news_default_img.jpg'

export const USERS = {
  AUTH: 'AUTH',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  REGISTER: 'REGISTER',
  GET_USERS: 'GET_USERS',
  GET_USER: 'GET_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
  ERRORS: 'ERRORS',
  CLEAN: 'CLEAN'
}

export const PROFILE = {
  GET_MYPROFILE: 'GET_MYPROFILE',
  GET_PROFILE: 'GET_PROFILE',
  GET_PROFILES: 'GET_PROFILES',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  DELETE_PROFILE: 'DELETE_PROFILE',
  ERRORS: 'ERRORS',
  CLEAN: 'CLEAN'
}

export const CLASSROOM = {
  GET_CLASSROOM: 'GET_CLASSROOM',
  GET_CLASSROOMS: 'GET_CLASSROOMS',
  ADD_CLASSROOM: 'ADD_CLASSROOM',
  UPDATE_CLASSROOM: 'UPDATE_CLASSROOM',
  DELETE_CLASSROOM: 'DELETE_CLASSROOM',
  ERRORS: 'ERRORS',
  CLEAN: 'CLEAN'
}

export const STUDENT = {
  GET_STUDENT: 'GET_STUDENT',
  GET_STUDENTS: 'GET_STUDENTS',
  UPDATE_STUDENT: 'UPDATE_STUDENT',
  DELETE_STUDENT: 'DELETE_STUDENT',
  ERRORS: 'ERRORS',
  CLEAN: 'CLEAN'
}

export const PARENT = {
  GET_PARENT: 'GET_PARENT',
  GET_PARENTS: 'GET_PARENTS',
  UPDATE_PARENT: 'UPDATE_PARENT',
  DELETE_PARENT: 'DELETE_PARENT',
  ERRORS: 'ERRORS',
  CLEAN: 'CLEAN'
}

export const STAFF = {
  GET_STAFF: 'GET_STAFF',
  GET_STAFFS: 'GET_STAFFS',
  UPDATE_STAFF: 'UPDATE_STAFF',
  DELETE_STAFF: 'DELETE_STAFF',
  ADD_STAFF: 'ADD_STAFF',
  ERRORS: 'ERRORS',
  CLEAN: 'CLEAN'
}

export const SCORE = {
  GET_SCORE: 'GET_SCORE',
  GET_SCORES: 'GET_SCORES',
  ADD_SCORE: 'ADD_SCORE',
  UPDATE_SCORE: 'UPDATE_SCORE',
  DELETE_SCORE: 'DELETE_SCORE',
  ERRORS: 'ERRORS',
  CLEAN: 'CLEAN'
}

export const COMPETITION = {
  GET_COMPETITION: 'GET_COMPETITION',
  GET_COMPETITIONS: 'GET_COMPETITIONS',
  ADD_COMPETITION: 'ADD_COMPETITION',
  UPDATE_COMPETITION: 'UPDATE_COMPETITION',
  DELETE_COMPETITION: 'DELETE_COMPETITION',
  ERRORS: 'ERRORS',
  CLEAN: 'CLEAN'
}

export const CLASSNEWS = {
  GET_CLASSNEWS: 'GET_CLASSNEWS',
  GET_CLASSNEWSS: 'GET_CLASSNEWSS',
  ADD_CLASSNEWS: 'ADD_CLASSNEWS',
  UPDATE_CLASSNEWS: 'UPDATE_CLASSNEWS',
  DELETE_CLASSNEWS: 'DELETE_CLASSNEWS',
  ERRORS: 'ERRORS',
  CLEAN: 'CLEAN'
}

export const PARENTNEWS = {
  GET_PARENTNEWS: 'GET_PARENTNEWS',
  GET_PARENTNEWSS: 'GET_PARENTNEWSS',
  ADD_PARENTNEWS: 'ADD_PARENTNEWS',
  UPDATE_PARENTNEWS: 'UPDATE_PARENTNEWS',
  DELETE_PARENTNEWS: 'DELETE_PARENTNEWS',
  ERRORS: 'ERRORS',
  CLEAN: 'CLEAN'
}

export const PARENTIN4 = {
  GET_PARENTIN4: 'GET_PARENTIN4',
  GET_PARENTIN4S: 'GET_PARENTIN4S',
  ADD_PARENTIN4: 'ADD_PARENTIN4',
  UPDATE_PARENTIN4: 'UPDATE_PARENTIN4',
  DELETE_PARENTIN4: 'DELETE_PARENTIN4',
  ERRORS: 'ERRORS',
  CLEAN: 'CLEAN'
}

export const NOTIFY = {
  GET_NOTIFY: 'GET_NOTIFY',
  GET_NOTIFIES: 'GET_NOTIFIES',
  ADD_NOTIFY: 'ADD_NOTIFY',
  UPDATE_NOTIFY: 'UPDATE_NOTIFY',
  DELETE_NOTIFY: 'DELETE_NOTIFY',
  ERRORS: 'ERRORS',
  CLEAN: 'CLEAN'
}

export const TOAST_TYPE = {
  SUCCESS: 'success',
  ERROR: 'error',
  INFO: 'info',
  WARNING: 'warning'
}

export const ROLES = {
  STUDENT: 'student',
  GUEST: 'guest',
  STAFF: 'staff',
  TEACHER: 'teacher',
  ADMIN: 'admin',
  PARENT: 'parent'
}
